
#ifndef SINGULARITY_VERSION_HPP
#define SINGULARITY_VERSION_HPP

#define SINGULARITY_LIB_MAJOR_VERSION 0
#define SINGULARITY_LIB_MINOR_VERSION 5
#define SINGULARITY_LIB_PATCH_VERSION 1

#define SINGULARITY_LIB_VERSION "0.5.1"

#endif /* SINGULARITY_VERSION_HPP */
