
#ifndef SINGULARITY_VERSION_HPP
#define SINGULARITY_VERSION_HPP

#define SINGULARITY_LIB_MAJOR_VERSION 0
#define SINGULARITY_LIB_MINOR_VERSION 8
#define SINGULARITY_LIB_PATCH_VERSION 4

#define SINGULARITY_LIB_VERSION "0.8.4"

#endif /* SINGULARITY_VERSION_HPP */
